### ISSUE TITLE
Permission denied when generating samples through python command

### ISSUE THREAD

**Issue by elenaraponi** [nikivanstein/GSAreport#27]
Command: `python GSAreport.py -p problem.json -d `pwd`/data --sample --samplesize 1000`

Output:
```
loaded problem definition
  0%|                                                                                                                                                                               | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "GSAreport.py", line 756, in <module>
    report = SAReport(
  File "GSAreport.py", line 138, in __init__
    os.makedirs(output_dir)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/output/'
```

Solution: Specify output folder path as last instruction: `python GSAreport.py -p problem.json -d `pwd`/data --sample --samplesize 1000 -o `pwd`/output`

**Comment by nikivanstein** [comment]
Will be fixed in next release
